name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Update about.md with build info
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          # Add build info to about.md
          cat >> docs/about.md << EOF
          
          
          ## 构建信息
          
          - **最后更新时间**: ${BUILD_TIME}
          - **Git 提交哈希**: \`${COMMIT_HASH}\`
          EOF

      - name: Build with VitePress
        run: bun run docs:build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}
          projectName: ${{ secrets.CLOUDFLARE_PAGES_NAME }}
          directory: docs/.vitepress/dist
          wranglerVersion: 3